# Generated by Django 5.0.2 on 2024-03-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resolved',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='updated_at',
        ),
    ]
