# Generated by Django 5.0.2 on 2024-04-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuesapp', '0003_issue_created_at_issue_image_issue_resolved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(default='images/no_image.jpg', upload_to='images'),
        ),
    ]
